proyecto_f/medicalapp/urls.py
from django.urls import path
from medicalapp.views import *
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('', inicio, name="Inicio"),
    path('registrarse/', registro, name="Registrarse"),
    path('login/', iniciosesion, name="Login"),
    path('agregar_avatar', agregarAvatar, name="AgregarAvatar"),
    path('sobre_mi', sobremi, name="SobreMi"),
    path('logout/', LogoutView.as_view(template_name="medicalapp/users/logout.html"), name="Logout"),
    path('editar_usuario/', editar_usuario, name="EditarUsuario"),
    path('lista_pacientes/', lista_pacientes, name="ListaPacientes"),
    path('lista_internados/', lista_internados, name="ListaInternados"),
    path('lista_hospitales/', lista_hospitales, name="ListaHospitales"),
    path('lista_medicos/', lista_medicos, name="ListaMedicos"),

    
    
    #CRUD
    path('eliminar_paciente/<pacienteDNI>/', eliminar_paciente, name="EliminarPaciente"),
    path('eliminar_internado/<pacienteDNI>/', eliminar_internado, name="EliminarInternado"),
    path('detalle_paciente/<pacienteDNI>/', editar_pacientes, name="DetallePacientes"),
    path('detalle_internado/<pacienteDNI>/', editar_internado, name="DetalleInternado"),
    path('agregar_medico/<medico_id>/', editar_medico, name="EditarMedico"),
    path('agregar_paciente/', agregar_paciente, name="AgregarPaciente"),
    path('agregar_internado/', agregar_internado, name="AgregarInternado"),

    ]

proyecto_f/proyecto_f/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render, redirect

def redireccion_inicio(request):
    return redirect('/MedicalDB/')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('MedicalDB/', include('medicalapp.urls')),
    path('', redireccion_inicio, name='redireccion-inicio'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto_f/medicalapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

#--------------------------------------------------------------------------------------

class Pacientes(models.Model):

        def __str__(self):
               return f"Nombre: {self.nombre} --- DNI:{self.documento}"
               
        documento = models.IntegerField(primary_key=True)
        nombre = models.CharField(max_length=60)
        apellido = models.CharField(max_length=60)
        sexo = models.CharField(max_length=60)
        nacimiento = models.DateField()
        u_consulta = models.DateField()
        medico = models.CharField(max_length=60)

#--------------------------------------------------------------------------------------

class PacientesInternados(models.Model):

        def __str__(self):
               return f"Nombre: {self.nombre} --- DNI:{self.documento}"
               
        documento = models.IntegerField(primary_key=True)
        nombre = models.CharField(max_length=60)
        apellido = models.CharField(max_length=60)
        sexo = models.CharField(max_length=60)
        nacimiento = models.DateField()
        fecha_ingreso = models.DateField()
        sala_asignada = models.CharField(max_length=60, default = "1A")
        medico = models.CharField(max_length=60)

#--------------------------------------------------------------------------------------

class Hospitales(models.Model):

        def __str__(self):
               return f"Nombre: {self.nombre} --- ID:{self.id}"
               
        id = models.IntegerField(primary_key=True)
        nombre = models.CharField(max_length=60)
        direccion = models.CharField(max_length=60)
        localidad = models.CharField(max_length=60)

#--------------------------------------------------------------------------------------

class Medicos(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    hospital = models.ForeignKey(Hospitales, on_delete=models.SET_NULL, null=True, blank=True)  
    rama_choices = (
        ('Traumatologo', 'Traumatologo'),
        ('Oftalmologo', 'Oftalmologo'),
        ('Enfermero', 'Enfermero'),
        ('Cirujano', 'Cirujano'),
    )
    rama = models.CharField(max_length=20, choices=rama_choices)
    numero_matricula = models.AutoField(primary_key=True)

    def __str__(self):
        return self.user.username
    
def save(self, *args, **kwargs):
        if self.numero_matricula is None:
            last_medico = Medicos.objects.order_by('-numero_matricula').first()
            if last_medico:
                self.numero_matricula = last_medico.numero_matricula + 1
            else:
                self.numero_matricula = 123456
        super(Medicos, self).save(*args, **kwargs)
        
#--------------------------------------------------------------------------------------

class Avatar(models.Model):
        usuario = models.ForeignKey(User, on_delete=models.CASCADE)
        imagen = models.ImageField(upload_to= "avatares", null=True, blank=True)

#--------------------------------------------------------------------------------------

RAMA_CHOICES = (
    ('Traumatologo', 'Traumatologo'),
        ('Oftalmologo', 'Oftalmologo'),
        ('Enfermero', 'Enfermero'),
        ('Cirujano', 'Cirujano'),
)

proyecto_f/medicalapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate
from medicalapp.models import *
from medicalapp.forms import *
from django.contrib.auth.decorators import login_required


#--------------------------------------------------------------------------------------



#--------------------------------------------------------------------------------------

#Vista de inicio

def inicio(request):
    return render(request, "medicalapp/inicio.html", {'mensaje':"Bienvenido", 'mensaje2':"Inicia sesion para comenzar a operar!"})

#--------------------------------------------------------------------------------------

#Vista sobre mi

def sobremi(request):
    return render(request, "medicalapp/sobremi.html")


#--------------------------------------------------------------------------------------

#Vista de registro

def registro(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)  # Asegúrate de incluir request.FILES
        if form.is_valid():
            user = form.cleaned_data.get('username')
            user_instance = form.save()

            # Guarda el avatar si se proporcionó una imagen
            avatar = form.cleaned_data.get('avatar')
            if avatar:
                avatar_obj = Avatar(usuario=user_instance, imagen=avatar)
                avatar_obj.save()

            return render(request, 'medicalapp/inicio.html', {'mensaje': 'Usuario Creado!'})

    else:
        form = RegistrationForm()
    return render(request, 'medicalapp/users/register.html', {'form': form})

#--------------------------------------------------------------------------------------

#Vista de login

def iniciosesion(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            usuario = form.cleaned_data["username"]
            contra = form.cleaned_data["password"]
            user = authenticate(request, username=usuario, password=contra)
            if user is not None:
                login(request, user)
                return render(request, "medicalapp/inicio.html", {'mensaje':'Bienvenido'})  
            else:
                return render(request, "medicalapp/inicio.html", {'mensaje':'Datos incorrectos'})
        else:
            mensaje = "Error, formulario erróneo"
    else:
        form = AuthenticationForm()
        
    return render(request, "medicalapp/users/login.html", {"form": form,})
    
   
#--------------------------------------------------------------------------------------

# Vista para editar el usuario

@login_required
def editar_usuario(request):
    usuario = request.user

    if request.method == 'POST':

        form = EditarUsuario(request.POST)

        if form.is_valid():
            datos = form.cleaned_data

            usuario.email = datos["email"]
            usuario.set_password(datos["password1"])
            usuario.first_name = datos["first_name"]
            usuario.last_name = datos["last_name"]

            usuario.save()
            login(request, usuario)

            return render(request, "medicalapp/inicio.html",{"mensaje":"Bienvenido "})
        
    else:

        form = EditarUsuario(initial=
            {'email':usuario.email,
             'first_name':usuario.first_name,
             'last_name':usuario.last_name,
             }
                              )
    return render(request, "medicalapp/users/editarUsuario.html", {'form':form , 'usuario':usuario})

#--------------------------------------------------------------------------------------

# Vista para agregar el avatar

@login_required
def agregarAvatar(request):

    if request.method == "POST":

        form = AvatarForm(request.POST, request.FILES)

        if form.is_valid():

            usuarioActual = User.objects.get(username=request.user)
            avatar = Avatar(usuario=usuarioActual, imagen=form.cleaned_data["imagen"])
            avatar.save()
            return render(request, "medicalapp/inicio.html")
    else:
        form = AvatarForm()

    return render(request, "medicalapp/users/agregarAvatar.html", {"form":form})


#--------------------------------------------------------------------------------------

#Lista de pacientes y buscadores

@login_required
def lista_pacientes(request):
    #Lista
    pacientes = Pacientes.objects.all()

    #Formulario de busqueda por DNI
    if 'buscar_dni' in request.GET:
        form_dni = BusquedaDNI(request.GET)
        if form_dni.is_valid():
            dni = form_dni.cleaned_data['dni']
            pacientes = Pacientes.objects.filter(documento=dni)
    else:
        form_dni = BusquedaDNI()

    #Formulario de búsqueda por médico
    if 'buscar_medico' in request.GET:
        form_doc = BusquedaDoc(request.GET)
        if form_doc.is_valid():
            doc = form_doc.cleaned_data['doc']
            pacientes = Pacientes.objects.filter(medico=doc)
    else:
        form_doc = BusquedaDoc()

    return render(request, 'medicalapp/funciones/listaPacientes.html', {'form_dni' : form_dni , 'form_doc' : form_doc , 'pacientes': pacientes})


#--------------------------------------------------------------------------------------

#Lista de pacientes internados y buscadores

@login_required
def lista_internados(request):
    #Lista
    pacientes = PacientesInternados.objects.all()

    #Formulario de busqueda por DNI
    if 'buscar_dni' in request.GET:
        form_dni = BusquedaDNI(request.GET)
        if form_dni.is_valid():
            dni = form_dni.cleaned_data['dni']
            pacientes = PacientesInternados.objects.filter(documento=dni)
    else:
        form_dni = BusquedaDNI()

    #Formulario de búsqueda por médico
    if 'buscar_medico' in request.GET:
        form_doc = BusquedaDoc(request.GET)
        if form_doc.is_valid():
            doc = form_doc.cleaned_data['doc']
            pacientes = PacientesInternados.objects.filter(medico=doc)
    else:
        form_doc = BusquedaDoc()

        #Formulario de búsqueda por sala
    if 'buscar_sala' in request.GET:
        form_sala = BusquedaSala(request.GET)
        if form_sala.is_valid():
            sala = form_sala.cleaned_data['sala']
            pacientes = PacientesInternados.objects.filter(sala_asignada=sala)
    else:
        form_sala = BusquedaSala()


    return render(request, 'medicalapp/funciones/listaInternados.html', {'form_dni' : form_dni , 'form_doc' : form_doc , 'form_sala' : form_sala, 'pacientes': pacientes})

#--------------------------------------------------------------------------------------

#Lista de pacientes y buscadores

@login_required
def lista_hospitales(request):
    #Lista
    hospitales = Hospitales.objects.all()

    #Formulario de busqueda por ID
    if 'buscar_id' in request.GET:
        form_id = BusquedaId(request.GET)
        if form_id.is_valid():
            id = form_id.cleaned_data['id']
            hospitales = Hospitales.objects.filter(id=id)
    else:
        form_id = BusquedaId()

    #Formulario de búsqueda por localidad
    if 'buscar_localidad' in request.GET:
        form_loc = BusquedaLocalidad(request.GET)
        if form_loc.is_valid():
            localidad = form_loc.cleaned_data['localidad']
            hospitales = Hospitales.objects.filter(localidad=localidad)
    else:
        form_loc = BusquedaLocalidad()

    return render(request, 'medicalapp/funciones/listaHospitales.html', {'form_id' : form_id , 'form_loc' : form_loc , 'hospitales': hospitales})

#--------------------------------------------------------------------------------------

#Lista de pacientes y buscadores

@login_required
def lista_medicos(request):
    usuarios_sin_perfil = User.objects.filter(medicos__isnull=True)
    for usuario in usuarios_sin_perfil:
        medico = Medicos(user=usuario)
        medico.save()

    medicos = Medicos.objects.all()

        #Formulario de búsqueda por médico
    if 'buscar_medico' in request.GET:
        form_doc = BusquedaDoc(request.GET)
        if form_doc.is_valid():
            doc = form_doc.cleaned_data['doc']
            medicos = Medicos.objects.filter(numero_matricula=doc)
    else:
        form_doc = BusquedaDoc()


    return render(request, 'medicalapp/funciones/listaMedicos.html', {'form_doc':form_doc , 'medicos': medicos})



#--------------------------------------------------------------------------------------


#Vista de pacientes

@login_required
def paciente(request, paciente_id):
    paciente = get_object_or_404(Pacientes, pk=paciente_id)
    return render(request, 'medicalapp/funciones/paciente.html', {'paciente': paciente})

#--------------------------------------------------------------------------------------

#Eliminar Paciente

@login_required
def eliminar_paciente(request, pacienteDNI):
     paciente = Pacientes.objects.get(documento=pacienteDNI)
     paciente.delete()

     pacientes = Pacientes.objects.all()

     return redirect('ListaPacientes')


#--------------------------------------------------------------------------------------

#Eliminar Internado

@login_required
def eliminar_internado(request, pacienteDNI):
     paciente = PacientesInternados.objects.get(documento=pacienteDNI)
     paciente.delete()

     pacientes = PacientesInternados.objects.all()

     return redirect('ListaInternados')


#--------------------------------------------------------------------------------------

#Agregar un paciente a la BD

@login_required
def agregar_paciente(request):
    if request.method == 'POST':
        form = FormularioPacientes(request.POST)
        if form.is_valid():
            datos = form.cleaned_data
            medico_numero_matricula = datos['medico']
            medico = Medicos.objects.get(numero_matricula=medico_numero_matricula)
            paciente = Pacientes(

proyecto_f/medicalapp/templates/medicalapp/formPacientes.html
{% extends "medicalapp/padre.html" %}

{% block top %}

<!------------------- Estilos para el formulario ------------------------------>

<style>
   
    .container-form {
        background-color: #fff;
        border: 1px solid #1ABC9C;
        border-radius: 8px;
        padding: 20px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        text-align: center;
        
    }

    h1 {
        color: #333;
        margin-bottom: 20px;
    }

    .patient-form {
        max-width: 400px;
        margin: 0 auto;
    }

    .submit-button {
        background-color: #1ABC9C;
        color: #fff;
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
        cursor: pointer;
    }

    input[type="text"], select {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #4F4F4F;
        border-radius: 4px;
    }

    #id_documento {
            display: inline-block;
            width: 100%;
            padding: 10px; 
            margin-right: 10px; /* Espaciado derecho para separar del siguiente campo */
        }
</style>

<!------------------- Formulario para agregar pacientes ------------------------------>

<div class="container-form">
    <h1>Agregar Paciente</h1>
    <form method="post" class="patient-form">
        {% csrf_token %}
        {{ miformulario.as_p }}
        <button type="submit" class="submit-button">Guardar</button>
    </form>
</div>


{% endblock %}

<!------------------- Pie de pagina ------------------------------>

{% block foot %}
<p style = "font-size: 20px;
color: #1ABC9C;
text-align: center;
margin-top: 10px;"> Todos los derechos reservados. </p>

{% endblock %}

proyecto_f/medicalapp/templates/medicalapp/inicio.html
{% extends "medicalapp/padre.html" %}

<!---------------- Mensaje de bienvenida --------------------->

{% block top %}

{% if request.user.is_not_authenticated %}

<p style="text-align: center; font-size: 100px; padding: 20px; border-radius: 5px; margin-top: 100px; margin-bottom: 50px;">
    {{ mensaje }}
</p>

<p style = "font-size: 20px;
color: #1ABC9C;
text-align: center;
margin-top: 10px; margin-bottom: 100px;">{{ mensaje2 }}</p>

{% else %}

<p style="text-align: center; font-size: 100px; padding: 20px; border-radius: 5px; margin-top: 100px; margin-bottom: 50px;">
    {{ mensaje }} {{user.first_name}}
</p>

{% with user.avatar_set.first as userAvatar %}
				{% if userAvatar %}
				<img src="{{userAvatar.imagen.url}}" alt="" style="max-width: 1000px; margin-left: 550px; margin-bottom: 100px;">
				{% endif %}
				{% endwith %}
{% endif%}

{% endblock %}

<!------------------- Pie de pagina ------------------------------>

{% block foot %}
<p style = "font-size: 20px;
color: #1ABC9C;
text-align: center;
margin-top: 10px;"> Todos los derechos reservados. </p>

{% endblock %}

proyecto_f/medicalapp/templates/medicalapp/paciente.html
{% extends "medicalapp/padre.html" %}

{% block top %}

 <!------------------- Estilos para el formulario ------------------------------>

<style>
    .container-form {
        background-color: #fff;
        border: 1px solid #1ABC9C;
        border-radius: 8px;
        padding: 20px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        text-align: center;
        
    }

    h1 {
        color: #333;
        margin-bottom: 20px;
    }

    .patient-form {
        max-width: 400px;
        margin: 0 auto;
    }

    .submit-button {
        background-color: #1ABC9C;
        color: #fff;
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
        cursor: pointer;
    }

    .delete-button {
        background-color: #1ABC9C;
        color: #fff;
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
        cursor: pointer;
        margin-top: 20px;
    }

    input[type="text"], select {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #4F4F4F;
        border-radius: 4px;
    }

    #id_documento {
            display: inline-block;
            width: 100%;
            padding: 10px; 
            margin-right: 10px;
        }
</style>

<!------------------- Formulario de paciente ------------------------------>

<div class="container-form">
    <h1>Agregar Paciente</h1>
    <form method="post" class="patient-form">
        {% csrf_token %}
        {{ miformulario.as_p }}
        <button type="submit" class="submit-button">Guardar</button>
    </form>

<!------------------- Boton para eliminar el paciente ------------------------------>

    <form method="post" action="{% url 'EliminarPaciente' pacienteDNI=documento %}" class="delete-form">
        {% csrf_token %}
        <button type="submit" class="delete-button">Eliminar Paciente</button>
    </form>
</div>

{% endblock %}

<!------------------- Pie de pagina ------------------------------>

{% block foot %}
<p style = "font-size: 20px;
color: #1ABC9C;
text-align: center;
margin-top: 10px;"> Todos los derechos reservados. </p>

{% endblock %}

proyecto_f/medicalapp/templates/medicalapp/padre.html
<!DOCTYPE html>
<html lang="en">
  <head>

	{% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Medical DB </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'medicalapp/assets/css/bootstrap.css' %}" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="{% static 'medicalapp/assets/css/main.css' %}" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'medicalapp/assets/js/hover.zoom.js' %}"></script>
    <script src="{% static 'medicalapp/assets/js/hover.zoom.conf.js' %}"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    
<!--------------------------------- Barra de navegacion ------------------------------------------->
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'Inicio' %}">Medical DB</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">

			{% if request.user.is_authenticated %}
				
				{% with user.avatar_set.first as userAvatar %}
				{% if userAvatar %}
				<a href="{% url 'EditarUsuario' %}"><img src="{{userAvatar.imagen.url}}" alt="" style="max-width: 100px;"></a>
				{% endif %}
				{% endwith %} 
				
				<li><a href="{% url 'ListaInternados' %}">Lista en Internacion</a></li>
				<li><a href="{% url 'ListaPacientes' %}">Lista de Pacientes</a></li>
				<li><a href="{% url 'ListaMedicos' %}">Medicos</a></li>
				<li><a href="{% url 'ListaHospitales' %}">Hospitales</a></li>
				<li><a href="{% url 'SobreMi' %}">Sobre mi</a></li>
				<li><a href="{% url 'Logout' %}">Salir</a></li>
			
			{% else %}

			<li><a href="{% url 'Login' %}">Ingresar</a></li>
            <li><a href="{% url 'Registrarse' %}">Registrarse</a></li>

			{% endif %}
            
            
            <!--<li><a href="contact.html">Contact</a></li>-->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

<!------------------- Cuerpo ------------------------------>

	{% block top %}
	<!-- 
	<div id="ww">
	    <div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2 centered">
					<img src="{% static 'medicalapp/assets/img/user.png' %}" alt="Stanley">
					<h1>Hi, I am Stanley!</h1>
					<p>Hello everybody. I'm Stanley, a free handsome bootstrap theme coded by BlackTie.co. A really simple theme for those wanting to showcase their work with a cute & clean style.</p>
					<p>Please, consider to register to <a href="http://eepurl.com/IcgkX">our newsletter</a> to be updated with our latest themes and freebies. Like always, you can use this theme in any project freely. Share it with your friends.</p>
				
				</div> /col-lg-8 -->
			<!--</div> /row -->
	    <!--</div>  /container -->
	<!--</div> /ww -->
	{% endblock %}
	
	<!-- +++++ Projects Section +++++ 
	
	<div class="container pt">
		<div class="row mt centered">	
			<div class="col-lg-4">
				<a class="zoom green" href="work01.html"><img class="img-responsive" src="{% static 'medicalapp/assets/img/portfolio/port01.jpg' %}" alt="" /></a>
				<p>APE</p>
			</div>
			<div class="col-lg-4">
				<a class="zoom green" href="work01.html"><img class="img-responsive" src="{% static 'medicalapp/assets/img/portfolio/port02.jpg' %}" alt="" /></a>
				<p>RAIDERS</p>
			</div>
			<div class="col-lg-4">
				<a class="zoom green" href="work01.html"><img class="img-responsive" src="{% static 'medicalapp/assets/img/portfolio/port03.jpg' %}" alt="" /></a>
				<p>VIKINGS</p>
			</div>-->
		</div><!-- /row 
		<div class="row mt centered">	
			<div class="col-lg-4">
				<a class="zoom green" href="work01.html"><img class="img-responsive" src="{% static 'medicalapp/assets/img/portfolio/port04.jpg' %}" alt="" /></a>
				<p>YODA</p>
			</div>
			<div class="col-lg-4">
				<a class="zoom green" href="work01.html"><img class="img-responsive" src="{% static 'medicalapp/assets/img/portfolio/port05.jpg' %}" alt="" /></a>
				<p>EMPERORS</p>
			</div>
			<div class="col-lg-4">
				<a class="zoom green" href="work01.html"><img class="img-responsive" src="{% static 'medicalapp/assets/img/portfolio/port06.jpg' %}" alt="" /></a>
				<p>CHIEFS</p>
			</div>-->
		</div><!-- /row -->
	</div><!-- /container -->
	
	
	<!------------------- Pie de pagina ------------------------------>
	
	<div id="footer">
		{% block foot %}
		{% endblock %}
	</div>
	

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'medicalapp/assets/js/bootstrap.min.js' %}"></script>
  </body>
</html>

proyecto_f/medicalapp/templates/medicalapp/register.html
{% extends "medicalapp/padre.html" %}
{% load static %}

{% block top %}

<!------------------- Estilos para el formulario ------------------------------>

<style>
    /* Estilos para el contenedor del formulario */
    .registration-container {
      max-width: 400px;
      margin: 0 auto;
      padding: 20px;
      border: 1px solid #ccc;
      border-radius: 5px;
      background-color: #f9f9f9;
    }
  
    /* Estilos para los campos de entrada */
    .registration-container input[type="text"],
    .registration-container input[type="email"],
    .registration-container input[type="password"],
    .registration-container input[type="number"] {
      width: 100%;
      padding: 10px;
      margin-bottom: 15px;
      border: 1px solid #ccc;
      border-radius: 3px;
    }
  
    /* Estilos para las etiquetas de los campos */
    .registration-container label {
      display: block;
      margin-bottom: 5px;
    }
  
    /* Estilos para el botón de registro */
    .registration-container button {
      background-color: #1ABC9C;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 3px;
      cursor: pointer;
    }
  
    /* Estilos para el botón de registro al pasar el mouse */
    .registration-container button:hover {
      background-color: #12725f;
    }
  </style>

<!------------------- Formulario de registro ------------------------------>

<div class="registration-container">
<h2>Registro de Usuario</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Registrarse</button>
  </form>
</div>

{% endblock %} 

<!------------------- Pie de pagina ------------------------------>

{% block foot %}
<p style = "font-size: 20px;
color: #1ABC9C;
text-align: center;
margin-top: 10px;"> Todos los derechos reservados. </p>

{% endblock %}